// Code generated by "stringer -type=ServerState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateIdle-0]
	_ = x[StateConnected-1]
	_ = x[StateError-2]
	_ = x[StateRetrying-3]
}

const _ServerState_name = "StateIdleStateConnectedStateErrorStateRetrying"

var _ServerState_index = [...]uint8{0, 9, 23, 33, 46}

func (i ServerState) String() string {
	if i < 0 || i >= ServerState(len(_ServerState_index)-1) {
		return "ServerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerState_name[_ServerState_index[i]:_ServerState_index[i+1]]
}
